#!/usr/bin/env bash
set -euo pipefail

# Resolve repo root and make your package importable once, up front (https://saturncloud.io/blog/how-to-get-the-directory-where-a-bash-script-is-located/)
ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
export PYTHONPATH="$ROOT/src${PYTHONPATH:+:$PYTHONPATH}"

cmd="${1:-}"

if [[ -z "$cmd" ]]; then
    echo "Usage: ./run install|test|<path_to_URL>"
    exit 1

elif [[ "$cmd" == "install" ]]; then
  python3 -m pip install --user -r "$ROOT/requirements.txt"
  exit 0

elif [[ "$cmd" == "test" ]]; then
  cd "$ROOT"
  python3 "$ROOT/src/ece461/test_summary.py"
  exit 0

else
  python3 -m ece461.main "$cmd"
  exit 0
fi
